Westgate: {
    User A
    User B
    User C
    User A.shape: person
    User B.shape: person
    User C.shape: person
    MSP-PaloAlto
}
DataCenter:{
    WGC-POSDB {
        WestgateWeb
        WESTGATELIVE
        WestgateWeb.shape: cylinder
        WESTGATELIVE.shape: cylinder
    }
    WGC-APP
    DC-PaloAlto
}

Westgate.User A <-> Westgate.MSP-PaloAlto
Westgate.User B <-> Westgate.MSP-PaloAlto
Westgate.User C <-> Westgate.MSP-PaloAlto
Westgate.MSP-PaloAlto <-> DataCenter.DC-PaloAlto: http/https
DataCenter.DC-PaloAlto <-> DataCenter.WGC-APP
DataCenter.WGC-App <-> DataCenter.WGC-POSDB.WestgateWeb: Read & Write
DataCenter.WGC-App <- DataCenter.WGC-POSDB.WESTGATELIVE: Readonly